# Generated by Django 4.0 on 2021-12-15 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rent',
            name='return_time',
            field=models.DateTimeField(blank=True),
        ),
    ]
